default['openphoto']['user'] = 'www-data'
default['openphoto']['group'] = 'www-data'
default['openphoto']['install_dir'] = '/srv/apps/openphoto'
default['openphoto']['data_dir'] = '/tank/appdata/openphoto'
default['openphoto']['repo'] = 'git://github.com/photo/frontend.git'
default['openphoto']['revision'] = 'cb721f0debcd66d8fe22ba60ea345917ec1344ec'
default['openphoto']['http_server_name'] = 'openphoto.mydomain.com'
default['openphoto']['database_flavor'] = 'mysql'